version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASEURL=http://localhost:4000/api
      - NEXT_PUBLIC_SECRET_KEY = SECRET

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT = 4000 SECRETKEY = TESTE EXPIRES_IN = 10000000

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
 
